Adding retry and fail for federation install script to avoid empty ce…
maistra/maistra-test-tool pull request #364
Opened 2023-01-30 17:30 UTC by fjglira

Adding retry and fail for install script for federation when the certificate retrieves root certificates for one of the mesh is empty (Related to https://issues.redhat.com/browse/OSSM-3237). Additionally, change the reference for the installation script to maistra 2.4 script

2023-01-30 20:45 UTC, yxun commented on pkg/federation/fed_single_cluster_install.go
> +		util.Log.Info("Reference: https://github.com/maistra/istio/blob/maistra-2.4/samples/federation/base/install.sh")
I think we should create a maistra-2.4 branch for this repo and then you can change your PR merge into maistra-2.4 branch

2023-01-31 07:12 UTC, pbajjuri20 requested changes

2023-01-31 07:12 UTC, pbajjuri20 commented on pkg/federation/fed_single_cluster_install.go
> +		util.Log.Info("Reference: https://github.com/maistra/istio/blob/maistra-2.4/samples/federation/base/install.sh")
It is good to have the 2.3 for the 2.3 branch

2023-01-31 10:24 UTC, fjglira commented on pkg/federation/fed_single_cluster_install.go
> +		util.Log.Info("Reference: https://github.com/maistra/istio/blob/maistra-2.4/samples/federation/base/install.sh")
Agree with @pbajjuri20 I'll make the changes for this log to reference the 2.3 doc and them we can create a new branch from this to have a new main 2.4 branch. Agree?

2023-01-31 13:14 UTC, fjglira commented on pkg/federation/fed_single_cluster_install.go
> +		util.Log.Info("Reference: https://github.com/maistra/istio/blob/maistra-2.4/samples/federation/base/install.sh")
Change made, after this merge will create a new branch 2.4 to track the new OSSM branch there

2023-01-31 13:16 UTC, fjglira commented
@jewertow Added improvement over the check of getting root certificate.
@yxun @pbajjuri20 Change mad over reference for install.sh script

2023-02-01 09:33 UTC, jewertow approved these changes

2023-02-08 14:28 UTC, yxun approved these changes

2023-02-09 14:24 UTC, merged